# Deploy website to GitHub pages

on:
  push:
    branches: [master, users/Helloworld/feature/auto-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install and Build
      run: |
        npm ci
        npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: master # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
        repository-name: LYZhelloworld/lyzhelloworld.github.io
        git-config-name: github-actions[bot]
        git-config-email: github-actions[bot]@users.noreply.github.com
        clean-exclude: README.md
        ssh-key: ${{ secrets.DEPLOY_KEY }}
